/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.KoneksiDB;
import config.UserSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YOGI
 */
public class CRUDjpembayaran extends javax.swing.JFrame {

    /**
     * Creates new form CRUDjpembayaran
     */
    String level = UserSession.get_level();

    public CRUDjpembayaran() {
        initComponents();
        tabelpembayaran();
        comboPeriode();
//        tIDpembayaran.setEnabled(false);
        btnupdate.setEnabled(false);
        tIDpembayaran.setText("Auto Fill");
    }
    Statement st;
    Connection con = KoneksiDB.getConnection();
    PreparedStatement pst;
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnrefresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbljenispem = new javax.swing.JTable();
        btnkembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tnamapembayaran = new javax.swing.JTextField();
        tIDpembayaran = new javax.swing.JTextField();
        biaya = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        tKelas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tperiode = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnrefresh.setBackground(new java.awt.Color(51, 51, 255));
        btnrefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh form");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 160, 48));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CARI PEMBAYARAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 200, 30));

        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });
        getContentPane().add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 470, 40));

        tbljenispem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbljenispem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbljenispemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbljenispem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 670, 320));

        btnkembali.setBackground(new java.awt.Color(51, 51, 255));
        btnkembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnkembali.setForeground(new java.awt.Color(255, 255, 255));
        btnkembali.setText("DASHBOARD");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 170, 50));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID PEMBAYARAN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("KELAS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("NAMA PEMBAYARAN");

        tnamapembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamapembayaranActionPerformed(evt);
            }
        });

        tIDpembayaran.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tIDpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIDpembayaranActionPerformed(evt);
            }
        });

        biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaActionPerformed(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(51, 51, 255));
        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(255, 102, 51));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UBAH");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(153, 153, 0));
        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        tKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelas 0", "Kelas 1", "Kelas 2", "Kelas 3" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("BIAYA ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PERIODE");

        tperiode.setMaximumRowCount(10);
        tperiode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tperiodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tIDpembayaran)
                            .addComponent(tnamapembayaran))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biaya)
                    .addComponent(tperiode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tIDpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tnamapembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tperiode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 360, 420));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KELOLA JENIS PEMBAYARAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 560, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-CRUD_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tnamapembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamapembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamapembayaranActionPerformed

    private void tIDpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIDpembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIDpembayaranActionPerformed

    private void biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaActionPerformed
        String nama = tnamapembayaran.getText();
        String Biaya = biaya.getText();
        String kelas = tKelas.getSelectedItem().toString();
        String periode = tperiode.getSelectedItem().toString();

        if (nama.length() == 0 || Biaya.length() == 0) {
            JOptionPane.showMessageDialog(null, "Masukan data dengan benar!!");

        } else {
            ID_AUTO();
            String id = tIDpembayaran.getText();

            try {
                String sql = "SELECT * FROM tbl_pembayaran where Nama_pembayaran='" + nama + "' AND group_kelas='" + kelas + "' AND Periode='" + periode + "'";
                rs = con.createStatement().executeQuery(sql);
                System.out.println(sql);
                if (rs.next()) {

                    JOptionPane.showMessageDialog(null, "Nama Pembayaran sudah dibuat pada periode dan grup kelas ini!!");

                } else {
                    System.out.println("masuk sini");
                    con.createStatement().executeUpdate("INSERT INTO tbl_pembayaran VALUE('" + id + "','" + nama + "','" + Biaya + "','" + kelas + "','" + periode + "')");
                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
                    Resetform();
                }
            } catch (Exception ex) {
                System.out.println("" + ex);
                JOptionPane.showMessageDialog(null, "Gagal !!" + ex);
            }
        }
    }//GEN-LAST:event_biayaActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {

            String nama = tnamapembayaran.getText();
            String harga = biaya.getText();
            String kelas = tKelas.getSelectedItem().toString();
            String periode = tperiode.getSelectedItem().toString();
            con.createStatement().executeUpdate("update tbl_pembayaran set Nama_pembayaran='" + nama + "',"
                    + "Biaya='" + harga + "',group_kelas='" + kelas + "',Periode='" + periode + "' "
                    + "where Kode_bayar ='" + model.getValueAt(tbljenispem.getSelectedRow(), 0) + "'");
            con.createStatement().executeUpdate("Update tbl_dettran set Hutang='" + harga + "' where "
                    + "Kode_bayar='" + model.getValueAt(tbljenispem.getSelectedRow(), 0) + "'");
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            Resetform();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
        tabelpembayaran();
    }//GEN-LAST:event_tCariActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        switch (level) {
            case "admin": {
                Dashboard dsb = new Dashboard();
                dsb.dashAdmin();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "petugas": {
                Dashboard dsb = new Dashboard();
                dsb.dashPetugas();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            default:
                break;
        }
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        String nama = tnamapembayaran.getText();
        String Biaya = biaya.getText();
        String kelas = tKelas.getSelectedItem().toString();
        String periode = tperiode.getSelectedItem().toString();

        if (nama.length() == 0 || Biaya.length() == 0) {
            JOptionPane.showMessageDialog(null, "Masukan data dengan benar!!");

        } else {

            ID_AUTO();
            String id = tIDpembayaran.getText();

            try {
                String sql = "SELECT * FROM tbl_pembayaran where Nama_pembayaran='" + nama + "' AND group_kelas='" + kelas + "' AND Periode='" + periode + "'";
                rs = con.createStatement().executeQuery(sql);
                if (rs.next()) {

                    JOptionPane.showMessageDialog(null, "Nama Pembayaran sudah dibuat pada periode dan grup kelas ini!!");
                    System.out.println(sql);

                } else {
                    System.out.println("masuk sini" + id);

                    con.createStatement().executeUpdate("INSERT INTO tbl_pembayaran VALUE('" + id + "','" + nama + "','" + Biaya + "','" + kelas + "','" + periode + "')");
                    //new feature to add pembayaran to tagihan siswa
                    String sqlCheckSiswa = "select *,tbl_kelas.group_kelas from tbl_setupkelas"
                            + " inner join tbl_kelas using(Kode_kelas)"
                            + " where Periode='" + periode + "' and group_kelas='" + kelas + "'";
                    System.out.println(sqlCheckSiswa);
                    try {
                        rs = con.createStatement().executeQuery(sqlCheckSiswa);
                        while (rs.next()) {
                            String idsiswa = rs.getString("kode_siswa");
                            String kodekelas = rs.getString("Kode_kelas");
                            try {
                                con.createStatement().executeUpdate("insert into tbl_dettran value('" + periode + "',"
                                        + "'" + idsiswa + "','" + kodekelas + "','" + id + "','" + Biaya + "','0','" + kelas + "')");
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "Gagal Menambahkan Tagihan Siswa " + e);
                                System.out.println(e);
                            }

                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error mendapatkan data siswa !! " + e);
                        System.out.println(e);
                    }

                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
                    Resetform();

                }

            } catch (Exception ex) {
                System.out.println("" + ex);
                JOptionPane.showMessageDialog(null, "Gagal !!" + ex);
            }
        }

    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        try {
            con.createStatement().executeUpdate("delete from tbl_pembayaran where Kode_bayar = '" + model.getValueAt(tbljenispem.getSelectedRow(), 0) + "'");
            JOptionPane.showMessageDialog(null, "Berhasil");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal !!!");

        }
        Resetform();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        Resetform();
        btnupdate.setEnabled(false);
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void tbljenispemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbljenispemMouseClicked
        int i = tbljenispem.getSelectedRow();
        tIDpembayaran.setText(model.getValueAt(i, 0).toString());
        tnamapembayaran.setText(model.getValueAt(i, 1).toString());
        biaya.setText(model.getValueAt(i, 2).toString());
        tKelas.setSelectedItem(model.getValueAt(i, 3).toString());
        tperiode.setSelectedItem(model.getValueAt(i, 4));

        //  disabled item on klik row table
        btnsimpan.setEnabled(false);
        btnupdate.setEnabled(true);
        tIDpembayaran.setEnabled(false);
    }//GEN-LAST:event_tbljenispemMouseClicked

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        tabelpembayaran();

    }//GEN-LAST:event_tCariKeyReleased

    private void tperiodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tperiodeActionPerformed

    }//GEN-LAST:event_tperiodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDjpembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDjpembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDjpembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDjpembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDjpembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biaya;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tIDpembayaran;
    private javax.swing.JComboBox<String> tKelas;
    private javax.swing.JTable tbljenispem;
    private javax.swing.JTextField tnamapembayaran;
    private javax.swing.JComboBox<String> tperiode;
    // End of variables declaration//GEN-END:variables

    private void tabelpembayaran() {
        String[] judul = {"Kode Pembayaran", "Nama Pembayaran", "Biaya", "Kelas", "Periode"};
        model = new DefaultTableModel(judul, 0);
        tbljenispem.setModel(model);
        String sql = "SELECT * FROM tbl_pembayaran where Nama_pembayaran like '%" + tCari.getText() + "%'OR Kode_bayar like '%" + tCari.getText() + "%' ORDER BY Kode_bayar DESC";

        try {
            Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String id = rs.getString("Kode_bayar");
                String nama = rs.getString("Nama_pembayaran");
                String bayar = rs.getString("Biaya");
                String kelas = rs.getString("group_kelas");
                String periode = rs.getString("Periode");

                String[] data = {id, nama, bayar.split("\\.")[0], kelas, periode};
                model.addRow(data);
            }
        } catch (Exception e) {
            System.out.println(e);

        }
    }

    private void comboPeriode() {
        String sql = "SELECT * FROM tbl_periode ORDER BY created_at DESC";

        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                tperiode.addItem(rs.getString("Periode"));

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void ID_AUTO() {
        try {
            String sql = "Select max(Kode_bayar) as no_idjpembayaran from tbl_pembayaran";
            Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    tIDpembayaran.setText("1");

                } else {
                    rs.last();
                    int autoid = rs.getInt(1) + 1;
                    String nomor = String.valueOf(autoid);

                    for (int a = 0; a < 1; a++) {
                        nomor = nomor;
                    }
                    System.out.println(nomor);
                    tIDpembayaran.setText(nomor);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "masukan data dengan benar!!");
        }
    }

    private void Resetform() {
        tIDpembayaran.setText("");
        tnamapembayaran.setText("");
        biaya.setText("");
        tKelas.setSelectedItem("Pilih Level");
        tabelpembayaran();

        btnsimpan.setEnabled(true);
        btnupdate.setEnabled(false);
        tIDpembayaran.setEnabled(true);
        tIDpembayaran.setEnabled(false);
        tIDpembayaran.setText("Auto Fill");

    }
}
