/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.KoneksiDB;
import config.*;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author YOGI
 */
public class Dashboard extends javax.swing.JFrame {

    Connection con = KoneksiDB.getConnection();
    ResultSet rs;
    DefaultTableModel model;

    //get user data session
    String id = UserSession.get_id();
    String username = UserSession.get_username();
    String nama = UserSession.get_nama();
    String level = UserSession.get_level();
    String tahunajaran = UserSession.getTahunajaran();
    String namaSekolah = sekolahSession.getNamaSekolah();
    String alamatSekolah = sekolahSession.getAlamatSekolah();

    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

    public Dashboard() {
        initComponents();
        txtnamasekolah.setText(namaSekolah);
        txtalamatsekolah.setText(alamatSekolah);
        tampiltransaksi();
        tanggal();
        jumlahDataMaster();

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        totaltransaksi();

    }

    public void dashSuper() {
//        jumlahDataMaster();
        t_Level.setText("SUPER ADMIN");
        t_user.setText(username);
        txtnamasekolah.setText(namaSekolah);
        txtalamatsekolah.setText(alamatSekolah);
    }

    public void dashAdmin() {
//        jumlahDataMaster();
        t_Level.setText("ADMINISTRATOR");
        t_user.setText(username);

        settingApp.setVisible(false);
        txtnamasekolah.setText(namaSekolah);
        txtalamatsekolah.setText(alamatSekolah);

    }

    public void dashPetugas() {
//        jumlahDataMaster();
        t_Level.setText("PETUGAS");
        t_user.setText(username);

        ppdb.setVisible(false);
        tambahjenispem.setVisible(false);
        settingApp.setVisible(false);
        tambahAdmin.setVisible(false);
        setTagihan.setVisible(false);
    }

    public void laporankelas() throws Exception {

        JasperDesign jd = JRXmlLoader.load(getClass().getResourceAsStream("/laporan/kelas.jrxml"));
        JRDesignQuery query = new JRDesignQuery();
        HashMap param = new HashMap();
        String namaSekolah = sekolahSession.getNamaSekolah();
        String alamatsekolah = sekolahSession.getAlamatSekolah();

        param.put("namaSekolah", namaSekolah);
        param.put("alamatSekolah", alamatsekolah);
        query.setText("select * from tbl_kelas");
        jd.setQuery(query);
        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
        JasperViewer.viewReport(jp, false);
    }

    public void laporanJenisPembayaran() throws Exception {
        JasperDesign jd = JRXmlLoader.load(getClass().getResourceAsStream("/laporan/jenisPembayaran.jrxml"));
        JRDesignQuery query = new JRDesignQuery();
        HashMap param = new HashMap();
        String namaSekolah = sekolahSession.getNamaSekolah();
        String alamatsekolah = sekolahSession.getAlamatSekolah();

        param.put("namaSekolah", namaSekolah);
        param.put("alamatSekolah", alamatsekolah);
        query.setText("select * from tbl_pembayaran");
        jd.setQuery(query);
        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
        JasperViewer.viewReport(jp, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        setupApp = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        inNamasekolah = new javax.swing.JTextField();
        inAlamatasekolah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        TA3 = new javax.swing.JLabel();
        jml_kelas = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TA2 = new javax.swing.JLabel();
        jml_admin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TA1 = new javax.swing.JLabel();
        jml_siswa = new javax.swing.JLabel();
        txtalamatsekolah = new javax.swing.JLabel();
        SistemP = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        t_Level = new javax.swing.JLabel();
        t_user = new javax.swing.JLabel();
        tTanggal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeltransaksi = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jumlahtransaksi = new javax.swing.JTextField();
        txtnamasekolah = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnAkun = new javax.swing.JMenu();
        InfoAkun = new javax.swing.JMenuItem();
        smLogout = new javax.swing.JMenuItem();
        mnDataMaster = new javax.swing.JMenu();
        tambahAdmin = new javax.swing.JMenuItem();
        tambahkelas = new javax.swing.JMenuItem();
        tambahjenispem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        setTagihan = new javax.swing.JMenuItem();
        settingApp = new javax.swing.JMenuItem();
        ppdb = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        Pembayaran = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        DaftarTransaksi = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setupApp.setMinimumSize(new java.awt.Dimension(674, 530));
        setupApp.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Set Up Application");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setupApp.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 674, -1));

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));

        inNamasekolah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        inAlamatasekolah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nama Sekolah");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Alamat Sekolah");

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("*note : Yang perlu dilakukan pertama agar siswa mendapatkan tagihan");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("1. Tambah nama siswa di fitur siswa");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("2. Kemudian tambahkan tahun ajaran di fitur siswa juga (Jika sudah ada, dilewati saja)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("3. Tambahkan kelas di fitur kelas (Jika sudah ada, dilewati saja)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("4. Tambahkan jenis pembayaran di fitur jenis pembayaran (Jika sudah ada, dilewati saja)");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("5. Alokasi kan siswa ke kelas yang sesuai");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inAlamatasekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inNamasekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inNamasekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inAlamatasekolah, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        setupApp.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 680, 480));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplikasi Pembayaran");
        setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Transaksi :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 220, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));

        TA3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TA3.setText("Kelas");

        jml_kelas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jml_kelas.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jml_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TA3)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jml_kelas)
                    .addComponent(TA3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 250, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        TA2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TA2.setText("Admin");

        jml_admin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jml_admin.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jml_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TA2)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TA2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jml_admin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 250, 50));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        TA1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TA1.setText("Siswa");

        jml_siswa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jml_siswa.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jml_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TA1)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TA1)
                    .addComponent(jml_siswa))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 250, 50));

        txtalamatsekolah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtalamatsekolah.setForeground(new java.awt.Color(255, 255, 255));
        txtalamatsekolah.setText("txtalamat");
        getContentPane().add(txtalamatsekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 360, 20));

        SistemP.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        SistemP.setForeground(new java.awt.Color(255, 255, 255));
        SistemP.setText("SISTEM PEMBAYARAN");
        getContentPane().add(SistemP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 570, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_Level.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t_Level.setText("Level");
        jPanel1.add(t_Level, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 30));

        t_user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t_user.setText("Nama User");
        jPanel1.add(t_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 220, 60));

        tTanggal.setEditable(false);
        tTanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tTanggal.setText("yyy/mm/dd");
        tTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTanggalActionPerformed(evt);
            }
        });
        getContentPane().add(tTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 120, 130, -1));

        tabeltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabeltransaksi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 910, 430));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tanggal :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 120, 80, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transaksi Hari Ini");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 320, 30));

        jumlahtransaksi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jumlahtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahtransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(jumlahtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 640, 280, 30));

        txtnamasekolah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtnamasekolah.setForeground(new java.awt.Color(255, 255, 255));
        txtnamasekolah.setText("txtnamasekolah");
        getContentPane().add(txtnamasekolah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 360, 20));

        bg.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg-dashboard.jpg"))); // NOI18N
        bg.setText("SISTEM PEMBAYARAN");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1370, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Transaksi Hari Ini");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 320, 30));

        mnAkun.setText("Akun");
        mnAkun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        InfoAkun.setText("Info Akun");
        InfoAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoAkunActionPerformed(evt);
            }
        });
        mnAkun.add(InfoAkun);

        smLogout.setText("Log Out");
        smLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smLogoutActionPerformed(evt);
            }
        });
        mnAkun.add(smLogout);

        jMenuBar1.add(mnAkun);

        mnDataMaster.setText("Data Master");
        mnDataMaster.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnDataMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDataMasterActionPerformed(evt);
            }
        });

        tambahAdmin.setText("Tambah Petugas");
        tambahAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahAdminActionPerformed(evt);
            }
        });
        mnDataMaster.add(tambahAdmin);

        tambahkelas.setText("Kelas");
        tambahkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkelasActionPerformed(evt);
            }
        });
        mnDataMaster.add(tambahkelas);

        tambahjenispem.setText("Jenis Pembayaran");
        tambahjenispem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahjenispemActionPerformed(evt);
            }
        });
        mnDataMaster.add(tambahjenispem);

        jMenu3.setText("Siswa");

        jMenuItem9.setText("Tambah Siswa");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Tahun Ajaran");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Alokasi Siswa");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        mnDataMaster.add(jMenu3);

        setTagihan.setText("Set Tagihan");
        setTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTagihanActionPerformed(evt);
            }
        });
        mnDataMaster.add(setTagihan);

        settingApp.setText("Setting App");
        settingApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingAppActionPerformed(evt);
            }
        });
        mnDataMaster.add(settingApp);

        ppdb.setText("PPDB");
        ppdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppdbActionPerformed(evt);
            }
        });
        mnDataMaster.add(ppdb);

        jMenuBar1.add(mnDataMaster);

        mnTransaksi.setText("Transaksi");
        mnTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Pembayaran.setText("Pembayaran Siswa");
        Pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembayaranActionPerformed(evt);
            }
        });
        mnTransaksi.add(Pembayaran);

        jMenuItem8.setText("Pembayaran (New)");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnTransaksi.add(jMenuItem8);

        DaftarTransaksi.setText("Daftar Transaksi");
        DaftarTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarTransaksiActionPerformed(evt);
            }
        });
        mnTransaksi.add(DaftarTransaksi);

        jMenuBar1.add(mnTransaksi);

        mnLaporan.setText("Laporan");
        mnLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenu1.setText("Master");

        jMenuItem1.setText("Kelas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Jenis Pembayaran");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Daftar SIswa Berdasarkan Kelas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        mnLaporan.add(jMenu1);

        jMenu2.setText("Transaksi");

        jMenuItem6.setText("Pembayaran");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem4.setText("Sudah Terbayar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem7.setText("Kekurangan Pembayaran");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        mnLaporan.add(jMenu2);

        jMenuBar1.add(mnLaporan);

        mnAbout.setText("About");
        mnAbout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAboutMouseClicked(evt);
            }
        });
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoAkunActionPerformed
        // TODO add your handling code here:
        new InfoAkun().setVisible(true);

    }//GEN-LAST:event_InfoAkunActionPerformed

    private void PembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembayaranActionPerformed
        Transaksi trx = new Transaksi();
        trx.setVisible(true);
        trx.setExtendedState(JFrame.MAXIMIZED_BOTH);
        if (level.equals("petugas")) {
            trx.button_set_tagihan.setVisible(false);
        }

        dispose();
    }//GEN-LAST:event_PembayaranActionPerformed

    private void smLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smLogoutActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_smLogoutActionPerformed

    private void tambahAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahAdminActionPerformed

        new CRUDadmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_tambahAdminActionPerformed

    private void tambahkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkelasActionPerformed
        new CRUDkelas().setVisible(true);
        dispose();
    }//GEN-LAST:event_tambahkelasActionPerformed

    private void tambahjenispemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahjenispemActionPerformed
        new CRUDjpembayaran().setVisible(true);
        dispose();
    }//GEN-LAST:event_tambahjenispemActionPerformed

    private void DaftarTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarTransaksiActionPerformed
        new DaftarTransaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_DaftarTransaksiActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        new about().setVisible(true);
    }//GEN-LAST:event_mnAboutActionPerformed

    private void tTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTanggalActionPerformed
        tanggal();
    }//GEN-LAST:event_tTanggalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        try {
            laporankelas();
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try {
            laporanJenisPembayaran();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new laporanKelas().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        LapPembayaran lp = new LapPembayaran();
        lp.setVisible(true);
        switch (level) {
            case "admin": {
                lp.cbUser.setEnabled(true);
                lp.cbUser.setSelectedItem(level);

                break;

            }
            case "petugas": {
                lp.cbUser.setEnabled(false);
                lp.cbUser.setSelectedItem(level);
            }
            default:
                break;
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new lapbayar().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void setTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTagihanActionPerformed
        // TODO add your handling code here:
        CRUDsetTagihan cst = new CRUDsetTagihan();
        cst.setVisible(true);
        cst.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
    }//GEN-LAST:event_setTagihanActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new laptagihan().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jumlahtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahtransaksiActionPerformed

    private void mnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAboutMouseClicked
        new about().setVisible(true);
    }//GEN-LAST:event_mnAboutMouseClicked

    private void settingAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingAppActionPerformed
        setupApp.setVisible(true);
        inNamasekolah.setText(namaSekolah);
        inAlamatasekolah.setText(alamatSekolah);
    }//GEN-LAST:event_settingAppActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            con.createStatement().executeUpdate("update tbl_setupapp set nama_sekolah='" + inNamasekolah.getText() + "',alamat_sekolah='" + inAlamatasekolah.getText() + "'");
            JOptionPane.showMessageDialog(null, "Ubah Nama Sekolah Berhasil");
            txtnamasekolah.setText(inNamasekolah.getText());
            txtalamatsekolah.setText(inAlamatasekolah.getText());
            sekolahSession.setNamaSekolah(inNamasekolah.getText());
            sekolahSession.setAlamatSekolah(inAlamatasekolah.getText());
            setupApp.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mnDataMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDataMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnDataMasterActionPerformed

    private void ppdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppdbActionPerformed
        dashboard_ppdb_backup dp = new dashboard_ppdb_backup();
        dp.setVisible(true);
        dp.setExtendedState(JFrame.MAXIMIZED_BOTH);

        dispose();
    }//GEN-LAST:event_ppdbActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Transaksi_new dp = new Transaksi_new();
        dp.setVisible(true);
        dp.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        CRUDsiswa cs = new CRUDsiswa();
        cs.setVisible(true);
        cs.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        CRUDta cta = new CRUDta();
        cta.setVisible(true);
//        cta.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed

        CRUDalosiswa cal = new CRUDalosiswa();
        cal.setVisible(true);
        cal.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });

    }

    private void jumlahDataMaster() {
        try {
            Statement stmtSiswa = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet Rowsiswa = stmtSiswa.executeQuery("SELECT * FROM tbl_siswa ");

            Statement stmtAdmin = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet Rowadmin = stmtAdmin.executeQuery("SELECT * FROM tbl_user");

            Statement stmtKelas = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet Rowkelas = stmtKelas.executeQuery("SELECT * FROM tbl_kelas");

            Rowsiswa.last();
            int totalSiswa = Rowsiswa.getRow();
            Rowsiswa.beforeFirst();
            jml_siswa.setText(Integer.toString(totalSiswa));

            Rowadmin.last();
            int totalAdmin = Rowadmin.getRow();
            Rowadmin.beforeFirst();
            jml_admin.setText(Integer.toString(totalAdmin));

            Rowkelas.last();
            int totalKelas = Rowkelas.getRow();
            Rowkelas.beforeFirst();
            jml_kelas.setText(Integer.toString(totalKelas));
        } catch (Exception e) {
            // Log the exception or provide a more informative error message
            System.err.println("Error: " + e.getMessage());

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DaftarTransaksi;
    private javax.swing.JMenuItem InfoAkun;
    private javax.swing.JMenuItem Pembayaran;
    private javax.swing.JLabel SistemP;
    private javax.swing.JLabel TA1;
    private javax.swing.JLabel TA2;
    private javax.swing.JLabel TA3;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField inAlamatasekolah;
    private javax.swing.JTextField inNamasekolah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jml_admin;
    private javax.swing.JLabel jml_kelas;
    private javax.swing.JLabel jml_siswa;
    private javax.swing.JTextField jumlahtransaksi;
    private javax.swing.JMenu mnAbout;
    private javax.swing.JMenu mnAkun;
    private javax.swing.JMenu mnDataMaster;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JMenuItem ppdb;
    private javax.swing.JMenuItem setTagihan;
    private javax.swing.JMenuItem settingApp;
    private javax.swing.JFrame setupApp;
    private javax.swing.JMenuItem smLogout;
    private javax.swing.JTextField tTanggal;
    private javax.swing.JLabel t_Level;
    private javax.swing.JLabel t_user;
    private javax.swing.JTable tabeltransaksi;
    private javax.swing.JMenuItem tambahAdmin;
    private javax.swing.JMenuItem tambahjenispem;
    private javax.swing.JMenuItem tambahkelas;
    private javax.swing.JLabel txtalamatsekolah;
    private javax.swing.JLabel txtnamasekolah;
    // End of variables declaration//GEN-END:variables

    private void tampiltransaksi() {
        tanggal();
        String[] judul = {"No Kwitansi", "Tanggal", "ID Siswa", "Nama Siswa", "Pembayaran", "Jumlah Bayar", "Petugas"};
        model = new DefaultTableModel(judul, 0);
        tabeltransaksi.setModel(model);
        String tanggal = tTanggal.getText();

        String sql = "SELECT tbl_siswa.Nama_siswa,tbl_transaksi.*,tbl_kelas.Nama_kelas,tbl_dettransaksi.jumlah,tbl_pembayaran.Nama_pembayaran"
                + " from tbl_transaksi INNER JOIN tbl_siswa Using(Kode_siswa)"
                + "  INNER JOIN tbl_kelas Using(Kode_kelas)"
                + " inner join tbl_dettransaksi Using(no_faktur)"
                + " Inner join tbl_pembayaran on tbl_dettransaksi.kode_biaya=tbl_pembayaran.Kode_bayar"
                + " where tanggal='" + tanggal + "'";

        try {
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String id = rs.getString("no_faktur");
                String tgl = rs.getString("tanggal");
                String kodesiswa = rs.getString("Kode_siswa");
                String nama = rs.getString("Nama_siswa");
                String kelas = rs.getString("Nama_pembayaran");
                String jml = rs.getString("jumlah").split("\\.")[0];
                String user = rs.getString("user");

                String[] data = {id, tgl, kodesiswa, nama, kelas, jml, user};
                model.addRow(data);

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void tanggal() {

        Calendar kal = new GregorianCalendar();
        int tahun = kal.get(Calendar.YEAR);
        int bulan = kal.get(Calendar.MONTH) + 1;
        int hari = kal.get(Calendar.DAY_OF_MONTH);

        if (bulan < 10) {
            String tanggal = tahun + "/0" + bulan + "/" + hari;
            tTanggal.setText(tanggal);
        } else {
            String tanggal = tahun + "/" + bulan + "/" + hari;

            tTanggal.setText(tanggal);
        }

    }

    public void totaltransaksi() {
        int total = 0;
        for (int i = 0; i < tabeltransaksi.getRowCount(); i++) {
            int amount = Integer.parseInt((String) tabeltransaksi.getValueAt(i, 5));
            total += amount;
        }
        jumlahtransaksi.setText("" + String.valueOf(kursIndonesia.format(total)));
    }

}
