/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.KoneksiDB;
import config.UserSession;
import config.sekolahSession;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author YOGI
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    String idpetugas = UserSession.get_id();
    String namapetugas = UserSession.get_username();
    String tahunAjaran = UserSession.getTahunajaran();
    String level = UserSession.get_level();

    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

    ArrayList list = new ArrayList<>();

    public Transaksi() {

        initComponents();
        tampiltagihan();
        tanggal();
        comboPeriode();

        namaadmin.setText(namapetugas);

        //set enable
        tkembalian.setEnabled(false);
        tTotal.setEnabled(false);
        btnhapus.setEnabled(false);
//        btnsimpan.setEnabled(false);
        tTanggal.setEnabled(false);

        btnpelunasan.setEnabled(false);
        btncetak.setEnabled(false);
        jmlbayar.setEnabled(false);

        //set mata uang
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);

    }
    Statement st;
    Connection con = KoneksiDB.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;
    DefaultTableModel modelbayar;
    PreparedStatement pst;

//    Calendar kalender = new GregorianCalendar();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form_view_siswa = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_siswa = new javax.swing.JTable();
        text_cari_siswa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tTanggal = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpembayaran = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltagihan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnbatal = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        jmltagihan = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tkembalian = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        namapembayaran = new javax.swing.JLabel();
        tTotal = new javax.swing.JTextField();
        btnhapus = new javax.swing.JButton();
        btnpelunasan = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jmlbayar = new javax.swing.JTextField();
        bayar1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        bayar2 = new javax.swing.JTextField();
        jbayar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        namasiswa = new javax.swing.JLabel();
        namaadmin = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tkelas = new javax.swing.JLabel();
        tIDsiswa = new javax.swing.JTextField();
        cbperiode = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tIDtransaksi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BTNkembali = new javax.swing.JButton();
        totalbayarBL = new javax.swing.JTextField();
        tIDkelas = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jmlhutang = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        button_set_tagihan = new javax.swing.JButton();
        BG = new javax.swing.JLabel();
        idjpBL = new javax.swing.JLabel();
        tkembaliBL = new javax.swing.JTextField();

        form_view_siswa.setLocation(new java.awt.Point(0, 0));
        form_view_siswa.setMinimumSize(new java.awt.Dimension(1097, 561));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tbl_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_siswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_siswa);

        text_cari_siswa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_cari_siswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_cari_siswaKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CARI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(text_cari_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cari_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout form_view_siswaLayout = new javax.swing.GroupLayout(form_view_siswa.getContentPane());
        form_view_siswa.getContentPane().setLayout(form_view_siswaLayout);
        form_view_siswaLayout.setHorizontalGroup(
            form_view_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        form_view_siswaLayout.setVerticalGroup(
            form_view_siswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tanggal :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 80, 80, 20));

        tTanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tTanggal.setText("yyy/mm/dd");
        getContentPane().add(tTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 70, 140, 30));

        tblpembayaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblpembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Bayar", "Nama Pembayaran", "Jumlah Bayar"
            }
        ));
        tblpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpembayaranMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblpembayaran);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 640, 220));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOTAL TAGIHAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 160, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DAFTAR TAGIHAN SISWA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 380, 50));

        tbltagihan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbltagihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbltagihan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbltagihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltagihanMouseClicked(evt);
            }
        });
        tbltagihan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbltagihanKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbltagihan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 640, 210));

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));

        btnbatal.setBackground(new java.awt.Color(153, 153, 255));
        btnbatal.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        btnbatal.setForeground(new java.awt.Color(255, 255, 255));
        btnbatal.setText("REFRESH");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btncetak.setBackground(new java.awt.Color(102, 102, 255));
        btncetak.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        btncetak.setForeground(new java.awt.Color(255, 255, 255));
        btncetak.setText("SIMPAN& CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        jmltagihan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jmltagihan.setText("Rp. 0,00");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("TAGIHAN              :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("JUMLAH BAYAR    :");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("KEMBALI              :");

        tkembalian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tkembalian.setText("0");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("PEMBAYARAN            :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("TOTAL                       :");

        namapembayaran.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        namapembayaran.setText("~");

        tTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tTotal.setText("0");

        btnhapus.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnpelunasan.setBackground(new java.awt.Color(0, 153, 153));
        btnpelunasan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpelunasan.setForeground(new java.awt.Color(255, 255, 255));
        btnpelunasan.setText("Pelunasan");
        btnpelunasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpelunasanActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText(" BAYAR                     :");

        jmlbayar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jmlbayar.setText("0");
        jmlbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlbayarActionPerformed(evt);
            }
        });

        bayar1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        bayar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bayar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayar1ActionPerformed(evt);
            }
        });
        bayar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayar1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btncetak)
                        .addGap(29, 29, 29)
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnpelunasan)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(namapembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jmlbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bayar1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(tkembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jmltagihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namapembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jmltagihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jmlbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpelunasan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 670, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bayar2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        bayar2.setText("Rp. 0,00");

        jbayar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbayar.setText("Bayar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbayar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bayar2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bayar2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 670, 90));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID SISWA         :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama Siswa      : ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kelas                  :");

        namasiswa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namasiswa.setForeground(new java.awt.Color(255, 255, 255));
        namasiswa.setText("~");

        namaadmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namaadmin.setForeground(new java.awt.Color(255, 255, 255));
        namaadmin.setText("~");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Petugas            :");

        tkelas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tkelas.setForeground(new java.awt.Color(255, 255, 255));
        tkelas.setText("~");

        tIDsiswa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tIDsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIDsiswaActionPerformed(evt);
            }
        });

        cbperiode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbperiode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Periode" }));
        cbperiode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbperiodeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No Kwitansi     :");

        tIDtransaksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tIDtransaksi.setForeground(new java.awt.Color(255, 255, 255));
        tIDtransaksi.setText("Auto Fill");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tIDsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(namasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(namaadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbperiode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tIDtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tIDsiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(cbperiode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(namaadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tIDtransaksi))
                        .addGap(446, 446, 446))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tkelas))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 670, 160));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM PEMBAYARAN SISWA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 560, 40));

        BTNkembali.setBackground(new java.awt.Color(0, 153, 153));
        BTNkembali.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        BTNkembali.setForeground(new java.awt.Color(255, 255, 255));
        BTNkembali.setText("DASHBOARD");
        BTNkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(BTNkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 50));

        totalbayarBL.setText("0");
        getContentPane().add(totalbayarBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 440, 180, 30));

        tIDkelas.setForeground(new java.awt.Color(255, 255, 255));
        tIDkelas.setText("1");
        getContentPane().add(tIDkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 244, 160, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PEMBAYARAN");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 210, 30));

        jmlhutang.setEditable(false);
        jmlhutang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jmlhutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlhutangActionPerformed(evt);
            }
        });
        getContentPane().add(jmlhutang, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 230, 30));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("TRANSAKSI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 130, 50));

        button_set_tagihan.setBackground(new java.awt.Color(0, 204, 204));
        button_set_tagihan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_set_tagihan.setText("Setting tagihan");
        button_set_tagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_set_tagihanActionPerformed(evt);
            }
        });
        getContentPane().add(button_set_tagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 150, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BG-pembayaran.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        idjpBL.setText("0");
        getContentPane().add(idjpBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 184, 150, 20));

        tkembaliBL.setText("0");
        getContentPane().add(tkembaliBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 510, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNkembaliActionPerformed
        switch (level) {
            case "admin": {
                Dashboard dsb = new Dashboard();
                dsb.dashAdmin();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            case "petugas": {
                Dashboard dsb = new Dashboard();
                dsb.dashPetugas();
                dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                dsb.setVisible(true);
                dispose();
                break;
            }
            default:
                break;
        }
    }//GEN-LAST:event_BTNkembaliActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        Resetform();
        DefaultTableModel dataModel = (DefaultTableModel) tblpembayaran.getModel();
        if (tblpembayaran.getRowCount() > 0) {
            for (int i = tblpembayaran.getRowCount() - 1; i > -1; i--) {
                dataModel.removeRow(i);

            }
        }
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        simpanpembayaran();
        updatetagihan();
        try {
            cetaknota();
        } catch (Exception ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        btncetak.setEnabled(false);
        DefaultTableModel dataModel = (DefaultTableModel) tblpembayaran.getModel();
        if (tblpembayaran.getRowCount() > 0) {
            for (int i = tblpembayaran.getRowCount() - 1; i > -1; i--) {
                dataModel.removeRow(i);
            }
        }
        Resetform();


    }//GEN-LAST:event_btncetakActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        DefaultTableModel dataModel = (DefaultTableModel) tblpembayaran.getModel();
        int i = tblpembayaran.getSelectedRow();
        dataModel.removeRow(i);
        totaltagihan();
        jbayar.setText("Bayar");
        bayar2.setText("Rp. 0,00");
        namapembayaran.setText("~");
        jmltagihan.setText("Rp. 0,00");
        tkembalian.setText("0");
        bayar1.setText("0");
        bayar1.setEnabled(true);
        idjpBL.setText("");

        btnhapus.setEnabled(false);

    }//GEN-LAST:event_btnhapusActionPerformed

    private void tbltagihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltagihanMouseClicked

        int i = tbltagihan.getSelectedRow();
        namapembayaran.setText(model.getValueAt(i, 1).toString());
        idjpBL.setText(model.getValueAt(i, 0).toString());

        double biaya = Double.parseDouble(model.getValueAt(i, 2).toString());//mengambil nilai untuk dihitung
        bayar1.setText((String) model.getValueAt(i, 2));

        jmltagihan.setText(String.valueOf(kursIndonesia.format(biaya)));//menampilkan nilai

        //  disabled item on klik row table
        btnbatal.setEnabled(true);

        jbayar.setText("Bayar");

    }//GEN-LAST:event_tbltagihanMouseClicked

    private void btnpelunasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpelunasanActionPerformed
        String cbTA = cbperiode.getSelectedItem().toString();
        String kodesiswa = tIDsiswa.getText();
        try {
            String sql = "SELECT *, tbl_pembayaran.Nama_pembayaran from tbl_dettran"
                    + " Inner join tbl_pembayaran USING(kode_bayar)"
                    + " where Kode_siswa='" + kodesiswa + "' and Hutang>'0' and tbl_dettran.Periode='" + cbTA + "'";
            rs = con.createStatement().executeQuery(sql);
            System.out.println(sql);

            while (rs.next()) {

                String nmpembayaran = rs.getString("Nama_pembayaran");
                String biaya = rs.getString("Hutang");
                String kodebayar = rs.getString("kode_bayar");
                DefaultTableModel dataModel = (DefaultTableModel) tblpembayaran.getModel();
                List list = new ArrayList<>();
                tblpembayaran.setAutoCreateColumnsFromModel(true);
                list.add(kodebayar);
                list.add(nmpembayaran);
                list.add(biaya);
                dataModel.addRow(list.toArray());

                int total = 0;
                for (int i = 0; i < tblpembayaran.getRowCount(); i++) {
                    int amount = Integer.parseInt((String) tblpembayaran.getValueAt(i, 2));
                    total += amount;
                }
                tTotal.setText("" + String.valueOf(kursIndonesia.format(total)));
                totalbayarBL.setText("" + total);
                btnpelunasan.setEnabled(false);
                bayar1.setEnabled(false);
                jmlbayar.setEnabled(true);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnpelunasanActionPerformed

    private void cbperiodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbperiodeActionPerformed
        tampilsiswa();
        tampiltagihan();
        totalhutang();
        btnpelunasan.setEnabled(true);


    }//GEN-LAST:event_cbperiodeActionPerformed

    private void jmlbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlbayarActionPerformed
        int total = Integer.parseInt(totalbayarBL.getText());
        int jmlbyr = Integer.parseInt(jmlbayar.getText());

        int kembalian = jmlbyr - total;

        if (kembalian < 0) {
            JOptionPane.showMessageDialog(null, "Uang masih kurang!!");
        } else {
            tkembalian.setText(String.valueOf(kursIndonesia.format(kembalian)));
            jbayar.setText("Kembalian");
            bayar2.setText(String.valueOf(kursIndonesia.format(kembalian)));
            tkembaliBL.setText(String.valueOf(kembalian));
            btncetak.setEnabled(true);
        }
    }//GEN-LAST:event_jmlbayarActionPerformed

    private void bayar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayar1ActionPerformed
        String kodebayar = idjpBL.getText();
        if (kodebayar.length() == 0) {
            JOptionPane.showMessageDialog(null, "Masukan Data dengan benar!!");

        } else {
            tablearray();
            tIDtransaksi.setText("Auto Fill");
            jbayar.setText("Bayar");
            bayar2.setText("Rp. 0,00");
            namapembayaran.setText("~");
            jmltagihan.setText("Rp. 0,00");
            tkembalian.setText("0");
            bayar1.setText("0");
            bayar1.setEnabled(true);
            idjpBL.setText("");

            btnhapus.setEnabled(false);
            jmlbayar.setEnabled(true);

        }


    }//GEN-LAST:event_bayar1ActionPerformed

    private void bayar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayar1KeyReleased
        double bayar = Double.parseDouble(bayar1.getText());
        bayar2.setText(String.valueOf(kursIndonesia.format(bayar)));
    }//GEN-LAST:event_bayar1KeyReleased

    private void tblpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpembayaranMouseClicked
        int i = tblpembayaran.getSelectedRow();
        DefaultTableModel dataModel = (DefaultTableModel) tblpembayaran.getModel();

        namapembayaran.setText(dataModel.getValueAt(i, 1).toString());
        int tagihan = Integer.parseInt((String) dataModel.getValueAt(i, 2));
        jmltagihan.setText(String.valueOf(kursIndonesia.format(tagihan)));
        idjpBL.setText(dataModel.getValueAt(i, 0).toString());
        bayar1.setText(dataModel.getValueAt(i, 2).toString());

        btnhapus.setEnabled(true);
        btnbatal.setEnabled(true);
        btncetak.setEnabled(true);
        jbayar.setText("Bayar");
        btnpelunasan.setEnabled(false);
        btncetak.setEnabled(false);
    }//GEN-LAST:event_tblpembayaranMouseClicked

    private void tbltagihanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbltagihanKeyPressed
        String kodebayar = idjpBL.getText();
        if (kodebayar.length() == 0) {
            JOptionPane.showMessageDialog(null, "Masukan Data dengan benar!!");

        } else {
            tablearray();
            tIDtransaksi.setText("Auto Fill");
            jbayar.setText("Bayar");
            bayar2.setText("Rp. 0,00");
            namapembayaran.setText("~");
            jmltagihan.setText("Rp. 0,00");
            tkembalian.setText("0");
            bayar1.setText("0");
            bayar1.setEnabled(true);
            idjpBL.setText("");

            btnhapus.setEnabled(false);
            jmlbayar.setEnabled(true);

        }
    }//GEN-LAST:event_tbltagihanKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        form_view_siswa.setVisible(true);
        viewSiswa();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmlhutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlhutangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlhutangActionPerformed

    private void tIDsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIDsiswaActionPerformed
        tampilsiswa();
    }//GEN-LAST:event_tIDsiswaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String kodesiswa = tIDsiswa.getText();
        String nmsiswa = namasiswa.getText();
        Transaksi_persiswa lb = new Transaksi_persiswa();
        lb.tIDsiswa.setText(kodesiswa);
        lb.namasiswa.setText(nmsiswa);
        lb.setVisible(true);
        lb.tampiltransaksi();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void button_set_tagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_set_tagihanActionPerformed
        if (level.equals("petugas")) {
            JOptionPane.showMessageDialog(null, "Hanya bisa diakses admin");
        } else {
            setting_tagihan st = new setting_tagihan();
            st.tIDsiswa.setText(tIDsiswa.getText());
            st.namasiswa.setText(namasiswa.getText());
            st.tperiode.setText(cbperiode.getSelectedItem().toString());
            st.setVisible(true);
            st.tabelSiswa();
        }
    }//GEN-LAST:event_button_set_tagihanActionPerformed

    private void tbl_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_siswaMouseClicked
        int i = tbl_siswa.getSelectedRow();
        DefaultTableModel dataModel = (DefaultTableModel) tbl_siswa.getModel();
        String kodesiswa = dataModel.getValueAt(i, 0).toString();
        String nama_siswa = dataModel.getValueAt(i, 1).toString();
        String kelas = dataModel.getValueAt(i, 4).toString();
        String idkelas = dataModel.getValueAt(i, 5).toString();

        tIDsiswa.setText(kodesiswa);
        namasiswa.setText(nama_siswa);
        tkelas.setText(kelas);
        tIDkelas.setText(idkelas);
        form_view_siswa.setVisible(false);
        
        btnpelunasan.setEnabled(true);
    }//GEN-LAST:event_tbl_siswaMouseClicked

    private void text_cari_siswaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_cari_siswaKeyReleased
viewSiswa();        // TODO add your handling code here:
    }//GEN-LAST:event_text_cari_siswaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Transaksi trx = new Transaksi();
                trx.setVisible(true);
                trx.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton BTNkembali;
    private javax.swing.JFormattedTextField bayar1;
    private javax.swing.JTextField bayar2;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnpelunasan;
    public javax.swing.JButton button_set_tagihan;
    private javax.swing.JComboBox<String> cbperiode;
    private javax.swing.JFrame form_view_siswa;
    private javax.swing.JLabel idjpBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jbayar;
    private javax.swing.JTextField jmlbayar;
    private javax.swing.JTextField jmlhutang;
    private javax.swing.JLabel jmltagihan;
    private javax.swing.JLabel namaadmin;
    private javax.swing.JLabel namapembayaran;
    public javax.swing.JLabel namasiswa;
    public javax.swing.JLabel tIDkelas;
    public javax.swing.JTextField tIDsiswa;
    private javax.swing.JLabel tIDtransaksi;
    private javax.swing.JTextField tTanggal;
    private javax.swing.JTextField tTotal;
    private javax.swing.JTable tbl_siswa;
    private javax.swing.JTable tblpembayaran;
    private javax.swing.JTable tbltagihan;
    private javax.swing.JTextField text_cari_siswa;
    public javax.swing.JLabel tkelas;
    private javax.swing.JTextField tkembaliBL;
    private javax.swing.JTextField tkembalian;
    private javax.swing.JTextField totalbayarBL;
    // End of variables declaration//GEN-END:variables

    private void tampilsiswa() {
        String cbTA = cbperiode.getSelectedItem().toString();
        String sql = "SELECT tbl_siswa.*,tbl_kelas.*"
                + " FROM tbl_setupkelas"
                + " INNER JOIN tbl_siswa USING(Kode_siswa)"
                + " INNER JOIN tbl_kelas USING(Kode_kelas)"
                + " where Kode_siswa='" + tIDsiswa.getText() + "' and Periode='" + cbTA + "'";
        try {
            rs = con.createStatement().executeQuery(sql);
            if (rs.next()) {
                tkelas.setText(rs.getString("Nama_kelas"));
                namasiswa.setText(rs.getString("Nama_siswa"));
                tIDkelas.setText(rs.getString("kode_kelas"));

                //belakang layar
                tampiltagihan();
                totalhutang();
//                tampilpembayaran();

            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Data Tidak Ada");
        }
    }

    public void ID_AUTO() {
        try {
            String sql = "Select max(right(no_faktur,5)) as no_idtransaksi from tbl_transaksi";
           Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    tIDtransaksi.setText("KWI-000001");

                } else {
                    rs.last();
                    int autoid = rs.getInt(1) + 1;
                    if (autoid <= 99) {
                        tIDtransaksi.setText("Kwi-0000" + autoid);
                    } else if (autoid > 99 && autoid <= 999) {
                        tIDtransaksi.setText("Kwi-000" + autoid);
                    } else if (autoid > 999) {
                        tIDtransaksi.setText("Kwi-00" + autoid);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error No Kwitansi");
        }
    }

    private void tampiltagihan() {
        String cbTA = cbperiode.getSelectedItem().toString();
        String kodesiswa = tIDsiswa.getText();

        String[] judul = {"Kode bayar", "Nama Tagihan", "Kurang Pembayaran"};
        model = new DefaultTableModel(judul, 0);
        tbltagihan.setModel(model);
        try {
            String sql = "SELECT *, tbl_pembayaran.Nama_pembayaran from tbl_dettran"
                    + " Inner join tbl_pembayaran USING(kode_bayar)"
                    + " where Kode_siswa='" + kodesiswa + "' and Hutang>'0' and tbl_dettran.Periode='" + cbTA + "'";
            rs = con.createStatement().executeQuery(sql);

            while (rs.next()) {

                String tagihan = rs.getString("Nama_pembayaran");
                String biaya = rs.getString("Hutang");
                String kodebayar = rs.getString("kode_bayar");
                

                String[] data = {kodebayar, tagihan, biaya.split("\\.")[0]};
                model.addRow(data);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void comboPeriode() {

        String sql = "SELECT * FROM tbl_periode ORDER BY created_at DESC";

        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                cbperiode.addItem(rs.getString("Periode"));

            }
        } catch (Exception e) {
        }
    }

    private void Resetform() {
        tIDtransaksi.setText("Auto Fill");
        jbayar.setText("Bayar");
        bayar2.setText("Rp. 0,00");
        namapembayaran.setText("~");
        jmltagihan.setText("Rp. 0,00");
        tTotal.setText("0");
        tkembalian.setText("0");
        bayar1.setText("0");
        bayar1.setEnabled(true);
        idjpBL.setText("");
        jmlbayar.setText("0");
        tkembaliBL.setText("0");
        jmlbayar.setEnabled(false);
        tampiltagihan();
        totalhutang();

        btnhapus.setEnabled(false);
        btncetak.setEnabled(false);

//        tampilpembayaran();
    }

    public void tanggal() {

        Calendar kal = new GregorianCalendar();
        int tahun = kal.get(Calendar.YEAR);
        int bulan = kal.get(Calendar.MONTH) + 1;
        int hari = kal.get(Calendar.DAY_OF_MONTH);
        if (bulan < 10) {
            String tanggal = tahun + "/0" + bulan + "/" + hari;
            tTanggal.setText(tanggal);
        } else {
            String tanggal = tahun + "/" + bulan + "/" + hari;

            tTanggal.setText(tanggal);
        }

    }

    public void simpanpembayaran() {
        ID_AUTO();
        String idsiswa = tIDsiswa.getText();
        String tanggal = tTanggal.getText();
        String idtransaksi = tIDtransaksi.getText();
        String periode = cbperiode.getSelectedItem().toString();
        String totalbayar = jmlbayar.getText();
        String user = namaadmin.getText();
        String idkelas = tIDkelas.getText();
        String kembalian = tkembaliBL.getText();
        System.out.println(idtransaksi);

        int jumlah_baris = tblpembayaran.getRowCount();
        if (jumlah_baris == 0) {
            JOptionPane.showMessageDialog(null, "Pembayaran Masih Kosong!");
        } else {
            try {
                con.createStatement().executeUpdate("INSERT INTO tbl_transaksi Value('" + idtransaksi + "',"
                        + "'" + tanggal + "','" + periode + "','" + idsiswa + "','" + idkelas + "','" + totalbayar + "','" + user + "','" + kembalian + "')");
                try {
                    int i = 0;
                    while (i < jumlah_baris) {
                        con.createStatement().executeUpdate("insert into tbl_dettransaksi(no_faktur,kode_biaya,jumlah)"
                                + " Values("
                                + "'" + idtransaksi + "','"
                                + "" + tblpembayaran.getValueAt(i, 0) + "','"
                                + "" + tblpembayaran.getValueAt(i, 2) + "')");
                        i++;

                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal Menyimpan!!" + e);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "input ke tbl_transaksi ada yang salah!!");
                System.out.println(e);
            }

        }

    }

    public void updatetagihan() {
        DefaultTableModel dataModel = (DefaultTableModel) tblpembayaran.getModel();
        String idsiswa = tIDsiswa.getText();

        int jumlahbaris = tblpembayaran.getRowCount();
        int i = 0;
        while (i < jumlahbaris) {
            String kodebayar = dataModel.getValueAt(i, 0).toString();
            String sql = "SELECT * from tbl_dettran where Kode_siswa='" + idsiswa + "' and Kode_bayar='" + kodebayar + "'";
            int bayar = Integer.parseInt(dataModel.getValueAt(i, 2).toString());
            try {
                rs = con.createStatement().executeQuery(sql);
                while (rs.next()) {
                    int hutang = Integer.parseInt(rs.getString("Hutang").split("\\.")[0]);
                    int lunas = Integer.parseInt(rs.getString("Lunas").split("\\.")[0]);

                    int updatehutang = hutang - bayar;
                    int updatelunas = lunas + bayar;
                    con.createStatement().executeUpdate("Update tbl_dettran set Hutang='" + updatehutang + "',"
                            + " Lunas='" + updatelunas + "' where Kode_siswa='" + idsiswa + "' and Kode_bayar='" + kodebayar + "'");

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println(e);
            }

            i++;
        }
        JOptionPane.showMessageDialog(null, "Berhasil Menyimpan!!");

    }

    public void tablearray() {

        //mengambil data periode
        String kodebayar = idjpBL.getText();
        String nmpembayaran = namapembayaran.getText();
        String bayar = bayar1.getText();

        DefaultTableModel dataModel = (DefaultTableModel) tblpembayaran.getModel();
        List list = new ArrayList<>();
        tblpembayaran.setAutoCreateColumnsFromModel(true);
        list.add(kodebayar);
        list.add(nmpembayaran);
        list.add(bayar);
        dataModel.addRow(list.toArray());
        totaltagihan();

    }

    public void totaltagihan() {
        int total = 0;
        for (int i = 0; i < tblpembayaran.getRowCount(); i++) {
            int amount = Integer.parseInt((String) tblpembayaran.getValueAt(i, 2));
            total += amount;
        }
        tTotal.setText("" + String.valueOf(kursIndonesia.format(total)));
        totalbayarBL.setText("" + total);
        btnpelunasan.setEnabled(false);
    }

    public void cetaknota() throws Exception {

        String total = tTotal.getText();
        JasperDesign jd = JRXmlLoader.load(getClass().getResourceAsStream("/laporan/notabayar.jrxml"));
        JRDesignQuery query = new JRDesignQuery();
        HashMap param = new HashMap();
        param.put("total", total);
        String namaSekolah = sekolahSession.getNamaSekolah();
        String alamatsekolah = sekolahSession.getAlamatSekolah();
        param.put("namaSekolah", namaSekolah);
        param.put("alamatSekolah", alamatsekolah);
        query.setText("select tbl_siswa.Nama_siswa,tbl_dettransaksi.*,tbl_transaksi.*,"
                + "tbl_pembayaran.Nama_pembayaran,tbl_kelas.Nama_kelas from tbl_transaksi "
                + " inner join tbl_siswa using(Kode_siswa) "
                + " INNER join tbl_dettransaksi USING(no_faktur) "
                + " inner join tbl_pembayaran on tbl_dettransaksi.kode_biaya=tbl_pembayaran.Kode_bayar"
                + " inner join tbl_kelas using(Kode_kelas) "
                + " where no_faktur='" + tIDtransaksi.getText() + "'");
        jd.setQuery(query);

        JasperReport jr = JasperCompileManager.compileReport(jd);
        JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
        JasperViewer.viewReport(jp, false);

    }

    public void totalhutang() {
        int total = 0;
        for (int i = 0; i < tbltagihan.getRowCount(); i++) {
            int amount = Integer.parseInt((String) tbltagihan.getValueAt(i, 2));
            total += amount;
        }
        jmlhutang.setText("" + String.valueOf(kursIndonesia.format(total)));
    }

    public void viewSiswa() {
        String[] judul = {"Kode Siswa", "Nama Siswa", "Alamat", "No Telepon", "Kelas", "Kode Kelas"};
        model = new DefaultTableModel(judul, 0);
        tbl_siswa.setModel(model);
        try {
            String sql = "SELECT *,tbl_setupkelas.*, tbl_kelas.Nama_kelas"
                    + " FROM tbl_setupkelas INNER join tbl_siswa using(Kode_siswa)"
                    + " inner join tbl_kelas using(kode_kelas)"
                    + " where Nama_siswa like'%" + text_cari_siswa.getText() + "%' OR Kode_siswa like '%" + text_cari_siswa.getText() + "' ORDER BY tbl_siswa.Kode_siswa DESC";
            System.out.println(sql);
            rs = con.createStatement().executeQuery(sql);
            while (rs.next()) {
                String kodesiswa = rs.getString("Kode_siswa");
                String namasiswa = rs.getString("Nama_siswa");
                String kelas = rs.getString("Nama_kelas");
                String kodekelas = rs.getString("Kode_kelas");
                String alamat = rs.getString("Alamat");
                String noTelepon = rs.getString("No_telepon");

                String[] data = {kodesiswa, namasiswa, alamat, noTelepon, kelas, kodekelas};
                model.addRow(data);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

}
